# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: Build Binaries

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build win-x86
      run: dotnet publish -r win-x86 -c Release /p:PublishSingleFile=true /p:PublishTrimmed=true
    - name: Build win-x64
      run: dotnet publish -r win-x64 -c Release /p:PublishSingleFile=true /p:PublishTrimmed=true
    - name: Build linux-x86
      run: dotnet publish -r linux-x86 -c Release /p:PublishSingleFile=true /p:PublishTrimmed=true
    - name: Build linux-x64
      run: dotnet publish -r linux-x64 -c Release /p:PublishSingleFile=true /p:PublishTrimmed=true
    - name: Test
      run: dotnet test --no-build --verbosity normal
