name: Build Binaries

on:
  workflow_dispatch:
  push:
    tags: [ "*" ]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.x
    - name: Setup Environment
      run: sudo apt-get install -y rename
    - name: Build
      run: bash ./scripts/build.sh
    - name: Upload To Artifact
      uses: actions/upload-artifact@v3
      with:
        name: PowerRename
        path: ./outputs/
    - name: Release
      uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: |
          ./outputs/win-x86/PowerRename-win-x86.exe
          ./outputs/win-x64/PowerRename-win-x64.exe
          ./outputs/linux-x64/PowerRename-linux-x64
          ./outputs/linux-arm64/PowerRename-linux-arm64
          ./outputs/linux-arm/PowerRename-linux-arm
